import logging
from google import genai
from google.genai.errors import APIError
from app.core.config import settings

logger = logging.getLogger(__name__)

_client: genai.Client | None = None


def get_gemini_client() -> genai.Client:
    """Initialize and return the Gemini client using environment variables.

    Raises:
        ValueError: If GEMINI_API_KEY is missing from environment.
    """
    global _client
    if _client is None:
        api_key = settings.GEMINI_API_KEY
        if not api_key:
            raise ValueError("GEMINI_API_KEY environment variable is not set")
        _client = genai.Client(api_key=api_key)
    return _client


def generate_response(prompt: str, model_name: str = "gemini-3.6-flash") -> str:
    """Send a user command/prompt to Gemini and return the generated text response.

    Args:
        prompt: The input prompt/command text.
        model_name: The Gemini model ID to use (default: 'gemini-3.6-flash').

    Returns:
        The text response generated by Gemini.

    Raises:
        ValueError: If prompt is empty or API key is missing.
        RuntimeError: If the API call fails or encounters an error.
    """
    if not prompt or not prompt.strip():
        raise ValueError("Prompt cannot be empty")

    try:
        client = get_gemini_client()
        response = client.models.generate_content(
            model=model_name,
            contents=prompt,
        )

        if not response or not response.text:
            raise RuntimeError("Gemini returned an empty response")

        return response.text.strip()

    except APIError as e:
        logger.error(f"Gemini API Error: {e}")
        raise RuntimeError(f"Gemini API Error: {e.message}") from e
    except Exception as e:
        logger.error(f"Error communicating with Gemini: {e}")
        raise RuntimeError(f"Gemini service error: {str(e)}") from e
